### ISSUE TITLE
Enable for lazy-helm/spacemacs/helm-find-files

### ISSUE THREAD

**Issue by fleimgruber** [yyoncho/helm-icons#2]
As hinted at in the issue name, using Spacemacs on latest develop branch. This works for `lazy-helm/helm-recentf` and `lazy-helm/helm-mini`, but not for `lazy-helm/spacemacs/helm-find-files`. From a quick glance at `helm-treemacs-icons-enable` I see `helm-source-ffiles` which should be the helm source that is ultimately used by `lazy-helm/spacemacs/helm-find-files`, should it not?

**Comment by yyoncho** [comment]
@fleimgruber it works but only if the enable call has been performed before loading helm - see https://github.com/yyoncho/helm-treemacs-icons/issues/1 .

**Comment by fleimgruber** [comment]
So then the config from README is stale since it calls enable _after_ loading helm? Installing helm-treemacs-icons via the github fetcher in a custom layer:

```
(defun mylayer/init-helm-treemacs-icons ()
  (with-eval-after-load 'helm
    (helm-treemacs-icons-enable)))
```

**Comment by fleimgruber** [comment]
Thanks for the quick one and thanks for all the great work!

**Comment by yyoncho** [comment]
FTR enable could be called even before helm has been loaded but should be called before the sources have been initialized. I want to have that changed.

As a side note, I will review the way the details are listed(and generally how it works in the context of spacemacs). For example, the buffers no longer need the major-mode in the list because of the icon which provides that context.
