### ISSUE TITLE
Adding this package to MELPA

### ISSUE THREAD

**Issue by daviderestivo** [yyoncho/helm-icons#7]
Hi @yyoncho,

thanks a lot for the nice package. I was wondering if and when you plan to include this package into MELPA :).

Regards,
Davide

**Comment by yyoncho** [comment]
I had I PR, but then I deleted it because I decided to change the package to helm-icons and support all the icons as well. But I never had the time to finish that.

But now I am planning to create a show-off lsp-mode focused emacs configuration, with all the fancy UI features and this package is part of the suite so I will do the Melpa onboarding relatively soon.

**Comment by daviderestivo** [comment]
Thanks a lot for the reply. Looking forward to see the new `helm-icons`.

**Comment by yyoncho** [comment]
https://github.com/melpa/melpa/pull/7017

**Comment by andersjohansson** [comment]
I made a working all-the-icons version here: https://gitlab.com/andersjohansson/helm-all-the-icons/-/blob/main/helm-all-the-icons.el
Some inspiration if you want to include the all-the-icons code.

It involves some unrelated changes (activation after loading instead of advising `helm-make-source`), which worked better for me right then, but which I doubt is better.

The problem with supporting both treemacs and all-the-icons is that there is no way to specify optional dependencies (for melpa) so both would be installed. I guess the solution would perhaps be to create two packages `helm-icons-treemacs` and `helm-icons-all-the-icons`  that depend on a common library `helm-icons` where the loading code etc. is defined (with some abstractions compared to the current state).

**Comment by yyoncho** [comment]
> The problem with supporting both treemacs and all-the-icons is that there is no way to specify optional dependencies

Optional deps can be expressed with define-function and dropping the explicit one and failing runtime with a message that the package is not present. We could create separate packages but IMO it will be overkill.
